#!/bin/bash

export HTTP_FULL_NODE_PORT=${HTTP_FULL_NODE_PORT:-8081}
export HTTP_SOLIDITY_PORT=${HTTP_SOLIDITY_PORT:-8082}
export RPC_PORT=${RPC_PORT:-50051}
export BLOCK_MAINTENANCE_INTERVAL=${BLOCK_MAINTENANCE_INTERVAL:-300000}
export BLOCK_PROPOSAL_EXPIRE_TIME=${BLOCK_PROPOSAL_EXPIRE_TIME:-30000}

envsubst < /tron/sr.conf.template > /tron/sr.conf
exec "$@"
